<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */echo __('* Required Fields') ?>">
    <legend class="legend">
        <span><?php /* @escapeNotVerified */echo __('Additional Information') ?></span>
    </legend>
    <br>
    <div class="field nickname required">
        <label class="label" for="email">
            <span><?= $block->escapeHtml(__('Nickname')) ?></span>
        </label>
        <div class="control">
            <input type="text" name="nickname" id="nickname" title="<?php /* @escapeNotVerified */echo __('My Attribute') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
        </div>
    </div>
</fieldset>
